const arr = [
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "Pants", offer: "30-70%off" },
  { cloth: "Kurta", offer: "50-80%off" },
  { cloth: "Pajama", offer: "20-50%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
  { cloth: "T-shirts", offer: "20-80%off" },
];

export default arr;
